services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    env_file:
      - ./.env
    environment:
      # Map DB_* from .env to the postgres expected vars
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - tsdb-data:/var/lib/postgresql/data
      - ./timescaledb/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - local

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - timescaledb
    env_file:
      - ./.env
    networks:
      - local
      - traefik-proxy
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    labels:
      # Configure Traefik for this container:
      - "traefik.enable=true"
      - "traefik.http.routers.sensorenr23-grafana.rule=Host(`${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.sensorenr23-grafana.entrypoints=websecure"
      - "traefik.http.routers.sensorenr23-grafana.tls=true"
      - "traefik.http.routers.sensorenr23-grafana.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-proxy"

  fetcher:
    build: ./fetcher
    container_name: sensor-fetcher
    depends_on:
      - timescaledb
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - local

volumes:
  tsdb-data:
  grafana-data:

networks:
  local:
  # In a separate docker-compose file, Traefik is set up with this network:
  traefik-proxy:
    external: true