apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    url: timescaledb:5432
    user: sensor_user
    secureJsonData:
      password: sensor_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600        # Postgres 16
      timescaledb: true
      database: sensor_data
